### ISSUE TITLE
Desenvolver regra de sessão: entidades, tabelas, relacionamentos e endpoints

### ISSUE THREAD

**Issue by lucasviinic** [lucasviinic/flashcard-forge-api#2]
Ao acessar um tópico o usuário pode iniciar uma sessão de estudos, isto é, ele pode praticar seus conhecimentos com os flashcards criados. A fim de registrar o desempenho do usuário, é necessário a criação de uma entidade que represente a sessão, além disso, o conjunto de registros de sessões podem ser úteis para que o usuário verifique seu histórico e progresso.

#### Session

| Tipo | Nome do campo | Descrição | Exemplo
| --- | --- | --- | --- |
| ID | topic_id | Chave estrangeira para Topics | 32 |
| TEXT | score | Score da sessão | 7/20 |
| INTERVAL | time | Duração da sessão de estudos | 00:09:31 |
| INT | easy | Quantidade de flashcards fáceis | 4 |
| INT | medium | Quantidade de flashcards médios | 10 |
| INT | hard | Quantidade de flashcards difíceis | 6 |
| TIMESTAMP | created_at | Data de criação do registro | 2023-07-15 18:42:23 |
| INT | updated_at | Data de atualização do registro | 2023-07-15 18:42:23 |
| INT | deleted_at | Data de deleção do registro | 2023-07-15 18:42:23 |

Além disso criar também uma tabela de junção, para associar a sessão aos flashcards respondidos. Ao final de cada sessão, onde N flashcards foram respondidos, N registros serão inseridos na tabela de junção SessionFlashcard:

#### SessionFlashcards

| Tipo       | Nome do campo | Descrição                         | Exemplo                |
|------------|---------------|-----------------------------------|------------------------|
| ID       | id            | Chave primária                    |                        |
| ID       | session_id    | Chave estrangeira para StudySession |                        |
| ID       | flashcard_id  | Chave estrangeira para Flashcard  |                        |
| BOOLEAN  | response      | Resposta dada (correta ou não)   |                        |
| INT      | difficulty    | Dificuldade do flashcard [0,1,2]         |                        |
| TIMESTAMP | created_at    | Data de criação do registro       | 2023-07-15 18:42:23    |
| TIMESTAMP | updated_at    | Data de atualização do registro   | 2023-07-15 18:42:23    |
| TIMESTAMP | deleted_at    | Data de deleção do registro       | 2023-07-15 18:42:23    |

### Endpoints

**[POST]** `/sessions`: Endpoint para registrar uma sessão, enviando objeto com os dados do tipo Session + a lista de flashcards respondidos. Retorna objeto do tipo Session.
**[GET]** `/sessions`: Informando o ID do tópico por query param. Retorna uma lista de Session com cada um contendo uma lista de Flashcards obtidos da tabela SessionFlashcard, com todas as sessões ordenadas da mais nova a mais antiga.

**Comment by lucasviinic** [comment]
### Tasks
- [ ] Criar tabelas Session e SessionFlashcard
- [ ] Criar entidades Session e SessionFlashcard
- [ ] Criar endpoint para registrar uma sessão
- [ ] Crar endpoint para obter todas as sessões realizadas com base no topic_id
